/// Generated by AssetsRefGenerator on 2021/10/06
class Res {
  static const String ar = "assets/lang/ar.json";
  static const String en = "assets/lang/en.json";
  static const String log1_01 = "assets/img/log1-01.png";
  static const String book = "assets/img/book.jpg";
}
